name: xapres
channels:
  - conda-forge
dependencies:
  - pytest
  - gcsfs
  - numpy
  - jupyter
  - jupyterlab
  - jupyter-book
  - xarray
  - pandas
  - tqdm
  - pip
  - zarr
  - dask
  - pip:
      - ipympl
      - sounddevice
      - soundfile
      - sphinx-inline-tabs
      - sphinx-examples
      - sphinx-proof
      - sphinx-hoverxref
      - sphinx-autodoc2
      - jupyter-book
      - bas-apres
