name: test_env_xapres
channels:
  - conda-forge
dependencies:
  - python=3.10
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - xarray
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - intake
  - fsspec
  - gcsfs
  - tqdm
  - pip
  - zarr


  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]