name: test_env_xapres_package
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - xarray
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - intake
  - fsspec
  - gcsfs
  - tqdm

  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]